version: '3'

networks:
    nginx-php70-mariadb10-node:

services:
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/project
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php70-service
        #            - mariadb10-service
        networks:
            - nginx-php70-mariadb10-node

    php70-service:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php70-container
        user: "1000:1000"
        ports:
            - 9090:9000
        volumes:
            - ./:/var/www/project
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
            - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
        networks:
            - nginx-php70-mariadb10-node

    mariadb10-service:
        image: mariadb:10
        container_name: mariadb10-container
        user: "1000:1000"
        ports:
            - 4306:3306
        #        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - nginx-php70-mariadb10-node

    node-service:
        image: node:latest
        container_name: node-container
        working_dir: /var/www/project
        user: "1000:1000"
        volumes:
            - ./:/var/www/project
        networks:
            - nginx-php70-mariadb10-node

#    unoconv-service:
#        build:
#            context: .
#            dockerfile: ./docker/unoconv-webservice/Dockerfile
#        container_name: unoconv-container
#        working_dir: /var/www/project/
#        user: "1000:1000"
#        ports:
#            - 3000:3000
#        volumes:
#            - ./:/var/www/project
#        networks:
#            - nginx-php70-mariadb10-node