fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

app:
    resource: '@AppBundle/Controller/'
    type: annotation

gcrmcrm:
    resource: "../../src/gcrm/crmbundle/Controller/"
    type: annotation
    prefix: /admin

easy_admin_file_panel_bundle:
    resource: "@EasyAdminFilePanelBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /admin

easy_admin_bundle:
    resource: "@GCRMCRMBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

wecoders_energy_bundle:
    resource: "@WecodersEnergyBundle/Controller/"
    type:     annotation
    prefix:   /admin

correspondence:
    resource: "@CorrespondenceBundle/Resources/config/routing.yml"
    prefix:   /admin