easy_admin:
    entities:
        Service:
            class: Wecoders\EnergyBundle\Entity\Service
            permissions: ['ROLE_SUPERADMIN']
            list:
                fields:
                    - id
                    - { property: 'title', label: 'Tytuł' }
                    - { property: 'gtu', label: 'GTU', template: '@GCRMCRMBundle/Default/admin/fields/option_array.html.twig', format: 'GCRM\CRMBundle\Service\GTU', class: 'getOptionByValue' }
                    - { property: 'netPrice', label: 'Wartość netto' }
                    - { property: 'vatPercentage', label: 'Vat (%)' }
                    - { property: 'precision', label: 'Precyzja' }
            form:
                fields:
                    - { property: 'title', label: 'Tytuł' }
                    - { property: 'gtu', label: 'GTU', type: 'choice', type_options: { required: false, multiple: false, expanded: false, placeholder: 'Pusta wartość', choices: {
                       'GTU_01': 1,
                       'GTU_02': 2,
                       'GTU_03': 3,
                       'GTU_04': 4,
                       'GTU_05': 5,
                       'GTU_06': 6,
                       'GTU_07': 7,
                       'GTU_08': 8,
                       'GTU_09': 9,
                       'GTU_10': 10,
                       'GTU_11': 11,
                       'GTU_12': 12,
                       'GTU_13': 13,
                       } } }
                    - { property: 'netPrice', label: 'Wartość netto' }
                    - { property: 'vatPercentage', label: 'Vat (%)' }
                    - { property: 'precision', label: 'Precyzja' }
