easy_admin:
    entities:
        DocumentProcess:
            class: GCRM\CRMBundle\Entity\Alert\DocumentProcess
            permissions: ['ROLE_SUPERADMIN']
            list:
                actions: ['show']
                fields:
                    - id
                    - { property: 'code', label: 'Kod' }
                    - { property: 'title', label: 'Tytuł' }
                    - { property: 'createdAt', label: 'Utworzone' }
            form:
                fields:
                    - { property: 'code', label: 'Kod' }
                    - { property: 'title', label: 'Tytuł' }
                    - { property: 'content', label: 'Zawartość' }