<?php

namespace GCRM\CRMBundle\Repository;

/**
 * AccountNumberIdentifierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountNumberIdentifierRepository extends \Doctrine\ORM\EntityRepository
{
}
