<?php

namespace GCRM\CRMBundle\Repository;

/**
 * CalculationCallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalculationCallRepository extends \Doctrine\ORM\EntityRepository
{
}
