<?php

namespace GCRM\CRMBundle\Repository;

/**
 * CampaignFieldTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaignFieldTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
