<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ChangeStatusLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeStatusLogRepository extends \Doctrine\ORM\EntityRepository
{
}
