<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ChargesGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChargesGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
