<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ClientProcedureTPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientProcedureTPRepository extends \Doctrine\ORM\EntityRepository
{
}
