<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ClientAndUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientAndUserRepository extends \Doctrine\ORM\EntityRepository
{
}
