<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractEnergyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractEnergyRepository extends \Doctrine\ORM\EntityRepository
{
}
