<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractAndServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractAndServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
