<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractAndTelephoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractAndTelephoneRepository extends \Doctrine\ORM\EntityRepository
{
}
