<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractTerminationTypeFormerServiceProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractTerminationTypeFormerServiceProviderRepository extends \Doctrine\ORM\EntityRepository
{
}
