<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractGasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractGasRepository extends \Doctrine\ORM\EntityRepository
{
}
