<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractSignPersonTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractSignPersonTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
