<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractShownDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractAndContractShownDocumentTypeBeforeSignRepository extends \Doctrine\ORM\EntityRepository
{
}
