<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractShownDocumentTypeBeforeSignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractShownDocumentTypeBeforeSignRepository extends \Doctrine\ORM\EntityRepository
{
}
