<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepositoryRepository extends \Doctrine\ORM\EntityRepository
{
}
