<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractEnergyAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractEnergyAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
