<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractGasAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractGasAndPriceListRepository extends \Doctrine\ORM\EntityRepository
{
}
