<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractAndCustomerAllowedDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractAndCustomerAllowedDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
