<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractAndTelephoneWithPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractAndTelephoneWithPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
