<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractAndTelephoneWithServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractAndTelephoneWithServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
