<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ContractProcessesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractProcessesRepository extends \Doctrine\ORM\EntityRepository
{
}
