<?php

namespace GCRM\CRMBundle\Repository;

/**
 * CustomerAllowedDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerAllowedDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
