<?php

namespace GCRM\CRMBundle\Repository;

/**
 * EndContractTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EndContractTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
