<?php

namespace GCRM\CRMBundle\Repository;

/**
 * InvoiceAndRabateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceAndRabateRepository extends \Doctrine\ORM\EntityRepository
{
}
