<?php

namespace GCRM\CRMBundle\Repository;

/**
 * InvoiceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
