<?php

namespace GCRM\CRMBundle\Repository;

/**
 * PackageToProcessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageToProcessRepository extends \Doctrine\ORM\EntityRepository
{
}
