<?php

namespace GCRM\CRMBundle\Repository;

/**
 * PackageToSendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageToSendRepository extends \Doctrine\ORM\EntityRepository
{
}
