<?php

namespace GCRM\CRMBundle\Repository;

/**
 * PackageToGenerate
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageToGenerate extends \Doctrine\ORM\EntityRepository
{
}
