<?php

namespace GCRM\CRMBundle\Repository;

/**
 * RabateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RabateRepository extends \Doctrine\ORM\EntityRepository
{
}
