<?php

namespace GCRM\CRMBundle\Repository;

/**
 * RecordingAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordingAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
