<?php

namespace GCRM\CRMBundle\Repository;

/**
 * RecordingGasAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordingGasAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
