<?php

namespace GCRM\CRMBundle\Repository;

/**
 * RecordingEnergyAttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordingEnergyAttachmentRepository extends \Doctrine\ORM\EntityRepository
{
}
