<?php

namespace GCRM\CRMBundle\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;
use GCRM\CRMBundle\Service\SellerModel;

/**
 * SellerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellerRepository extends \Doctrine\ORM\EntityRepository
{
    public static $em;

    public function __construct(EntityManager $em, Mapping\ClassMetadata $class)
    {
        self::$em = $em;
        parent::__construct($em, $class);
    }

    public static function energyRecords()
    {
        return self::getRecordsByType(SellerModel::OPTION_ENERGY);
    }

    public static function gasRecords()
    {
        return self::getRecordsByType(SellerModel::OPTION_GAS);
    }

    public static function getRecordsByType($type)
    {
        $qb = self::$em->createQueryBuilder();
        $q = $qb->select(['a'])
            ->from('GCRMCRMBundle:Seller', 'a')
            ->where('a.option = :type')
            ->setParameters([
                'type' => $type
            ])
        ;
        return $q;
    }
}
