<?php

namespace GCRM\CRMBundle\Repository;

/**
 * ServiceProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceProviderRepository extends \Doctrine\ORM\EntityRepository
{
}
