<?php

namespace GCRM\CRMBundle\Repository;

/**
 * StatusContractControlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusContractControlRepository extends \Doctrine\ORM\EntityRepository
{
}
