<?php

namespace GCRM\CRMBundle\Repository;

/**
 * StatusClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusClientRepository extends \Doctrine\ORM\EntityRepository
{
}
