<?php

namespace GCRM\CRMBundle\Repository;

/**
 * StatusContractActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusContractActionRepository extends \Doctrine\ORM\EntityRepository
{
}
