<?php

namespace GCRM\CRMBundle\Repository;

/**
 * StatusContractAdministrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusContractAdministrationRepository extends \Doctrine\ORM\EntityRepository
{
}
