<?php

namespace GCRM\CRMBundle\Repository;

/**
 * StatusClientVerificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusClientVerificationRepository extends \Doctrine\ORM\EntityRepository
{
}
