<?php

namespace GCRM\CRMBundle\Repository;

/**
 * StatusAuthorizationDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusAuthorizationDepartmentRepository extends \Doctrine\ORM\EntityRepository
{
}
