<?php

namespace GCRM\CRMBundle\Repository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;

/**
 * StatusContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusContractRepository extends \Doctrine\ORM\EntityRepository
{
    public static $em;

    public function __construct(EntityManager $em, Mapping\ClassMetadata $class)
    {
        self::$em = $em;
        parent::__construct($em, $class);
    }

    public static function authorizationRecords()
    {
        return self::statusContractsByIds(
            self::getStatusContractsIdsFromStatusContractSelectedDepartmentEntity('GCRMCRMBundle:StatusContractAuthorization')
        );
    }

    public static function verificationRecords()
    {
        return self::statusContractsByIds(
            self::getStatusContractsIdsFromStatusContractSelectedDepartmentEntity('GCRMCRMBundle:StatusContractVerification')
        );
    }

    public static function administrationRecords()
    {
        return self::statusContractsByIds(
            self::getStatusContractsIdsFromStatusContractSelectedDepartmentEntity('GCRMCRMBundle:StatusContractAdministration')
        );
    }

    public static function controlRecords()
    {
        return self::statusContractsByIds(
            self::getStatusContractsIdsFromStatusContractSelectedDepartmentEntity('GCRMCRMBundle:StatusContractControl')
        );
    }

    public static function processRecords()
    {
        return self::statusContractsByIds(
            self::getStatusContractsIdsFromStatusContractSelectedDepartmentEntity('GCRMCRMBundle:StatusContractProcess')
        );
    }

    public static function financesRecords()
    {
        return self::statusContractsByIds(
            self::getStatusContractsIdsFromStatusContractSelectedDepartmentEntity('GCRMCRMBundle:StatusContractFinances')
        );
    }

    private static function getStatusContractsIdsFromStatusContractSelectedDepartmentEntity($entity)
    {
        $statusContractIds = [];
        $contracts = self::$em->getRepository($entity)->findAll();
        foreach ($contracts as $contract) {
            $statusContract = $contract->getStatusContract();
            if (!$statusContract) {
                continue;
            }

            $statusContractIds[] = $statusContract->getId();
        }
        return $statusContractIds;
    }

    private static function statusContractsByIds($ids)
    {
        $qb = self::$em->createQueryBuilder();
        $q = $qb->select(['a'])
            ->from('GCRMCRMBundle:StatusContract', 'a')
            ->where('a.id IN (:ids)')
            ->setParameters([
                'ids' => $ids
            ])
        ;
        return $q;
    }
}
