<?php

namespace GCRM\CRMBundle\Repository;

/**
 * StatusContractVerificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusContractVerificationRepository extends \Doctrine\ORM\EntityRepository
{
}
