<?php

namespace GCRM\CRMBundle\Repository;

/**
 * StatusContractAuthorizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusContractAuthorizationRepository extends \Doctrine\ORM\EntityRepository
{
}
