<?php

namespace GCRM\CRMBundle\Repository;

/**
 * StatusDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusDepartmentRepository extends \Doctrine\ORM\EntityRepository
{
}
