<?php

namespace GCRM\CRMBundle\Repository;

/**
 * TariffAndServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TariffAndServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
