<?php

namespace GCRM\CRMBundle\Repository;

/**
 * UserAndBranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAndBranchRepository extends \Doctrine\ORM\EntityRepository
{
}
