<?php

namespace GCRM\CRMBundle\Repository;

/**
 * UserAndCompanyWithBranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAndCompanyWithBranchRepository extends \Doctrine\ORM\EntityRepository
{
}
