<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * CustomDocumentTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomDocumentTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
