<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * DocumentPackageToGenerateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentPackageToGenerateRepository extends \Doctrine\ORM\EntityRepository
{
}
