<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * DocumentPackageToGenerateRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentPackageToGenerateRecordRepository extends \Doctrine\ORM\EntityRepository
{
}
