<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * DocumentBankAccountChangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentBankAccountChangeRepository extends \Doctrine\ORM\EntityRepository
{
}
