<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * DocumentTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentTableRepository extends \Doctrine\ORM\EntityRepository
{
}
