<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * EnergyDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnergyDataRepository extends \Doctrine\ORM\EntityRepository
{
}
