<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * ExciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExciseRepository extends \Doctrine\ORM\EntityRepository
{
}
