<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * MergeInvoicesPackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MergeInvoicesPackageRepository extends \Doctrine\ORM\EntityRepository
{
}
