<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * MergeInvoicesPackageRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MergeInvoicesPackageRecordRepository extends \Doctrine\ORM\EntityRepository
{
}
