<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * OsdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OsdRepository extends \Doctrine\ORM\EntityRepository
{
}
