<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * PackageToGenerateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageToGenerateRepository extends \Doctrine\ORM\EntityRepository
{
}
