<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * PriceListDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceListDataRepository extends \Doctrine\ORM\EntityRepository
{
}
