<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * PriceListGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceListGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
