<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * SmsClientGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsClientGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
