<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * SmsMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
