<?php

namespace Wecoders\EnergyBundle\Repository;

/**
 * TariffTreatLikeLastSettlementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TariffTreatLikeLastSettlementRepository extends \Doctrine\ORM\EntityRepository
{

}
