<?php

namespace Wecoders\InvoiceBundle\Repository;

/**
 * InvoiceNumberSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceNumberSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
