exporter_bundle:
    tables:
        InvoiceEstimatedSettlementCorrectionOptimaTemplate:
            class: Wecoders\EnergyBundle\Entity\InvoiceEstimatedSettlementCorrection
            filter: Wecoders\EnergyBundle\Service\Exporter\InvoiceDataFilter
            tweaker: Wecoders\EnergyBundle\Service\Exporter\InvoiceOptimaTweaker
            alias: i
            fields:
                - { property: 'i.number', label: 'Numer faktury' }
                - { property: 'ip.number', alias: 'invoice_id', label: 'Numer dokumentu korygowanego' }
                - { property: "'1'", label: 'Czy dokument to korekta' }
                - { property: 'c.id', label: 'ID Nabywcy' }
                - { property: 'i.clientFullName', label: 'Nabywca pełna nazwa' }
                - { property: 'i.clientCity', label: 'Nabywca miasto' }
                - { property: 'i.clientStreet', label: 'Nabywca ulica' }
                - { property: 'i.clientHouseNr', label: 'Nabywca numer domu' }
                - { property: 'i.clientApartmentNr', label: 'Nabywca numer lokalu' }
                - { property: 'i.clientZipCode', label: 'Nabywca kod pocztowy' }
                - { property: 'i.clientNip', label: 'Nabywca NIP' }
                - { property: 'i.payerCompanyName', label: 'Płatnik pełna nazwa' }
                - { property: 'i.payerCity', label: 'Płatnik miasto' }
                - { property: 'i.payerStreet', label: 'Płatnik ulica' }
                - { property: 'i.payerHouseNr', label: 'Płatnik numer domu' }
                - { property: 'i.payerApartmentNr', label: 'Płatnik numer lokalu' }
                - { property: 'i.payerZipCode', label: 'Płatnik kod pocztowy' }
                - { property: 'i.payerNip', label: 'Płatnik NIP' }
                - { property: 'i.dateOfPayment', label: 'Termin płatności' }
                - { property: 'i.createdDate', label: 'Data wystawienia' }
                - { property: 'i.includedDocuments', alias: 'included_documents', label: 'DOKUMENTY WCHODZACE W SKLAD' }
                - { property: 'i.summaryNetValue', alias: 'summary_net_value', label: 'Kwota netto' }
                - { property: 'i.summaryVatValue', alias: 'summary_vat_value', label: 'Kwota VAT' }
                - { property: 'i.summaryGrossValue', alias: 'summary_gross_value', label: 'Kwota brutto' }
                - { property: "'PLN'", label: 'Waluta' }
                - { property: 'i.exciseValue', alias: 'excise_value', label: 'Wartość akcyzy' }
                - { property: 'i.isPaid', type: 'yesno', label: 'Opłacona Tak/Nie' }
                - { property: 'i.clientAccountNumber', label: 'Sprzedawca numer rachunku' }
                - { property: 'i.type', label: 'TYP' }

                - { property: 'ip.includedDocuments', alias: 'invoice_included_documents', label: 'FAKTURA - DOKUMENTY WCHODZACE W SKLAD' }
                - { property: 'ip.summaryNetValue', alias: 'invoice_summary_net_value', label: 'FAKTURA - KWOTA NETTO' }
                - { property: 'ip.summaryVatValue', alias: 'invoice_summary_vat_value', label: 'FAKTURA - KWOTA VAT' }
                - { property: 'ip.summaryGrossValue', alias: 'invoice_summary_gross_value', label: 'FAKTURA - KWOTA BRUTTO' }
                - { property: 'ip.exciseValue', alias: 'invoice_excise_value', label: 'WARTOSC AKCYZY' }

                - { property: 'i.gtu1', label: 'GTU_01' }
                - { property: 'i.gtu2', label: 'GTU_02' }
                - { property: 'i.gtu3', label: 'GTU_03' }
                - { property: 'i.gtu4', label: 'GTU_04' }
                - { property: 'i.gtu5', label: 'GTU_05' }
                - { property: 'i.gtu6', label: 'GTU_06' }
                - { property: 'i.gtu7', label: 'GTU_07' }
                - { property: 'i.gtu8', label: 'GTU_08' }
                - { property: 'i.gtu9', label: 'GTU_09' }
                - { property: 'i.gtu10', label: 'GTU_10' }
                - { property: 'i.gtu11', label: 'GTU_11' }
                - { property: 'i.gtu12', label: 'GTU_12' }
                - { property: 'i.gtu13', label: 'GTU_13' }
                - { property: 'i.transactionProcedure1', label: 'SW' }
                - { property: 'i.transactionProcedure2', label: 'EE' }
                - { property: 'i.transactionProcedure3', label: 'TP' }
                - { property: 'i.transactionProcedure4', label: 'TT_WNT' }
                - { property: 'i.transactionProcedure5', label: 'TT_D' }
                - { property: 'i.transactionProcedure6', label: 'MR_T' }
                - { property: 'i.transactionProcedure7', label: 'MR_UZ' }
                - { property: 'i.transactionProcedure8', label: 'I_42' }
                - { property: 'i.transactionProcedure9', label: 'I_63' }
                - { property: 'i.transactionProcedure10', label: 'B_SPV' }
                - { property: 'i.transactionProcedure11', label: 'B_SPV_DOSTAWA' }
                - { property: 'i.transactionProcedure12', label: 'B_MPV_PROWIZJA' }
                - { property: 'i.transactionProcedure13', label: 'MPP' }

            joinTables:
                - { class: 'Wecoders\EnergyBundle\Entity\InvoiceEstimatedSettlement', alias: 'ip', condition: 'i.invoice = ip.id' }
                - { class: 'GCRM\CRMBundle\Entity\Client', alias: 'c', condition: 'i.client = c.id' }
