exporter_bundle:
    tables:
        Payment:
            class: GCRM\CRMBundle\Entity\Payment
            alias: p
            filter: GCRM\CRMBundle\Service\Exporter\PaymentDataFilter
            groupBy: p.id
            options:
                inc_row_number: true
            fields:
                - { property: 'c.id', alias: 'client_id', label: 'ID klienta'}
                - { property: 'p.badgeId', label: 'ID rachunku'}
                - { property: 'p.value', label: 'Kwota'}
                - { property: 'p.senderBranchNumber', label: 'Numer oddziału nadawcy'}
                - { property: 'p.receiverBranchNumber', label: 'Numer oddziału odbiorcy'}
                - { property: 'p.senderAccountNumber', label: 'Numer rachunku nadawcy'}
                - { property: 'p.receiverAccountNumber', label: 'Numer rachunku odbiorcy'}
                - { property: 'p.senderName', label: 'Nazwa nadawcy'}
                - { property: 'p.receiverName', label: 'Nazwa odbiorcy'}
                - { property: 'p.date', label: 'Data płatności'}
                - { property: 'p.help', label: 'Dodatkowa informacja' }
                - { property: 'p.createdAt', label: 'Data utworzenia rekordu'}

            joinTables:
                - { class: 'GCRM\CRMBundle\Entity\AccountNumberIdentifier', alias: 'ani', condition: 'p.badgeId = ani.number' }
                - { class: 'GCRM\CRMBundle\Entity\Client', alias: 'c', condition: 'c.accountNumberIdentifier = ani.id' }